services:
  db:
    image: postgres:17
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hsuadmin
      POSTGRES_PASSWORD: hsu123
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./data:/data
      - ./init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: hsu234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

volumes:
  local_pgdata:
  pgadmin-data:
