magic_shop:
  target: raw
  outputs:
    raw:
      type: clickhouse
      host: localhost
      port: 8123
      user: hsuadmin
      password: hsu123
      secure: False
      verify: False
      schema: raw
      threads: 4
    analytics:
      type: clickhouse
      host: localhost
      port: 8123
      user: hsuadmin
      password: hsu123
      secure: False
      verify: False
      schema: analytics
      threads: 4