services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: hsuadmin
      CLICKHOUSE_PASSWORD: hsu123
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
